name: Check Booking

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-booking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24'
        check-latest: true
    - name: Get dependencies
      run: |
        go get undercover-bookie-go
    - name: Run build
      run: go build . 
    - name: Check booking
      env:
        BOOKING_URL: ${{ secrets.BOOKING_URL }}
        TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
        AUTOMATED_CHECK_CONFIG: ${{ secrets.AUTOMATED_CHECK_CONFIG }}
      if: env.TELEGRAM_API_KEY != null
      run: |
            while IFS="," read -r rec_column1 rec_column2 rec_column3 rec_column4
            do
                echo "Movie : $rec_column1"
                echo "Event : $rec_column2"
                echo "regionSlug : $rec_column3"
                echo "regionCode : $rec_column4"
                ./undercover-bookie-go "Book tickets" $rec_column2 $rec_column3 $rec_column4 @undercoverbookie
            done < <(tail -n +2 $GITHUB_WORKSPACE/resources/checklist.csv)
