name: Create artifact on tag

on:
  push:
    tags:
      - '*'

jobs:
  attach-artifact:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run build
      run: go build . 
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: undercover-bookie-go
        tag: ${{ github.ref }}
        overwrite: true