name: Integration Check

on: 
  push: 
  pull_request:
    branches:
    - master

jobs:
  integration:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.0-rc.1'
    - name: Run build
      run: go build . 
    # - name: Run testing
    #   run: cd test && go test -v